[book]
title = "rbspy: A Sampling CPU Profiler for Ruby"
authors = ["Adam Jensen and Julia Evans, with contributions from the rbspy community"]
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/rbspy/rbspy.github.io"
